---
- name: Populate countries
  shell: "DB_MIGRATION_USER={{ COMMON_MYSQL_MIGRATE_USER }} DB_MIGRATION_PASS={{ COMMON_MYSQL_MIGRATE_PASS }} {{ ecommerce_venv_dir }}/bin/python ./manage.py oscar_populate_countries --initial-only"
  args:
    chdir: "{{ ecommerce_code_dir }}"
  become_user: "{{ ecommerce_user }}"
  environment: "{{ ecommerce_environment }}"
  when: migrate_db is defined and migrate_db|lower == "yes"
  tags:
    - migrate
    - migrate:db

- name: Create Apple Pay certificates directory
  file:
    path: "{{ ecommerce_apple_pay_merchant_certificate_directory }}"
    state: directory
    owner: "{{ supervisor_user }}"
    group: "{{ common_web_user }}"
  tags:
    - install
    - install:configuration

- name: Write Apple Pay merchant certificates
  copy:
    content: "{{ ECOMMERCE_APPLE_PAY_MERCHANT_CERTIFICATE }}"
    dest: "{{ ecommerce_apple_pay_merchant_certificate_path }}"
    owner: "{{ supervisor_user }}"
    group: "{{ common_web_user }}"
    mode: "0644"
  no_log: true
  tags:
    - install
    - install:configuration

- name: Create site for multi-tenancy
  shell: '{{ ecommerce_venv_dir }}/bin/python ./manage.py create_or_update_site --site-id=1 --site-domain={{ ECOMMERCE_ECOMMERCE_URL_ROOT.split("://")[1] }} --partner-code=edX --partner-name="Open edX" --lms-url-root={{ ECOMMERCE_LMS_URL_ROOT }} --client-side-payment-processor=cybersource --payment-processors=cybersource,paypal --client-id={{ ECOMMERCE_SOCIAL_AUTH_EDX_OIDC_KEY }} --client-secret={{ ECOMMERCE_SOCIAL_AUTH_EDX_OIDC_SECRET }} --from-email staff@example.com --discovery_api_url={{ ECOMMERCE_DISCOVERY_SERVICE_URL }}/api/v1/'
  args:
    chdir: "{{ ecommerce_code_dir }}"
  become_user: "{{ ecommerce_user }}"
  environment: "{{ ecommerce_environment }}"
  when: ecommerce_create_demo_data
  tags:
    - install

- name: Create demo data
  shell: '{{ ecommerce_venv_dir }}/bin/python ./manage.py create_demo_data --partner=edX'
  args:
    chdir: "{{ ecommerce_code_dir }}"
  become_user: "{{ ecommerce_user }}"
  environment: "{{ ecommerce_environment }}"
  when: ecommerce_create_demo_data
  tags:
    - install
