---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role ecommerce
#
# Overview:
#
#
# Dependencies:
#
#
# Example play:
#
#
- name: Populate countries
  shell: "DB_MIGRATION_USER={{ COMMON_MYSQL_MIGRATE_USER }} DB_MIGRATION_PASS={{ COMMON_MYSQL_MIGRATE_PASS }} {{ ecommerce_venv_dir }}/bin/python ./manage.py oscar_populate_countries --initial-only"
  args:
    chdir: "{{ ecommerce_code_dir }}"
  become_user: "{{ ecommerce_user }}"
  environment: "{{ ecommerce_environment }}"
  when: migrate_db is defined and migrate_db|lower == "yes"
  tags:
    - migrate
    - migrate:db

- name: Create Apple Pay certificates directory
  file:
    path: "{{ ecommerce_apple_pay_merchant_certificate_directory }}"
    state: directory
    owner: "{{ supervisor_user }}"
    group: "{{ common_web_user }}"
  tags:
    - install
    - install:configuration

- name: Write Apple Pay merchant certificates
  copy:
    content: "{{ ECOMMERCE_APPLE_PAY_MERCHANT_CERTIFICATE }}"
    dest: "{{ ecommerce_apple_pay_merchant_certificate_path }}"
    owner: "{{ supervisor_user }}"
    group: "{{ common_web_user }}"
    mode: "0644"
  no_log: true
  tags:
    - install
    - install:configuration
